author: 'Isaac Adewumi'
name: 'hashnode-blog'
description: 'Publish posts to Hashnode by pushing Markdown files to a GitHub repository.'

# Branding appears on GitHub Marketplace
branding:
  icon: 'upload'
  color: 'blue'

# Define input parameters
inputs:
  replicate-api-key:
    description: 'The Replicate API key for authentication.'
    required: false

  access-token:
    description: 'The Hashnode API access token.'
    required: true

  posts-directory:
    description: 'The local directory containing the blog posts.'
    required: false
    default: 'posts'

  supported-formats:
    description: 'The allowed file formats for blog posts.'
    required: false
    default: 'md'

  publication-id:
    description: 'The ID of the publication to publish the posts to.'
    required: true

runs:
  using: node20
  main: dist/index.js
